## NumPy (www.numpy.org)

NumPy is important in scientific computing, it is coded both in Python and C++ (for speed). A few important features for Numpy are:

a powerful N-dimensional array object

sophisticated broadcasting functions

tools for integrating C/C++ and Fortran code

useful linear algebra, Fourier transform, and random number capabilities

Next, we will introduce Numpy arrays, which are related to the data structures.

In order to use Numpy module, we need to import it first. A conventional way to import it is to use “np” as a shortened name using

```python
import numpy as np
```

Numpy has a detailed guide for users migrating from Matlab. Just google 'Numpy for Matlab Users'

In [1]:
import numpy as np

If the previously line produces an error, then you need to install numpy.
Please type
```python
!pip install numpy 
```

In [25]:
#to create an array, we use the numpy funcion array
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

Arrays are entered by rows, each row is defined as a list. To create a 2d array, simply use nested lists

In [9]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

The arrays created with numpy are objects (instances of a class) and have many atributes associated with them. For example, the shape of an array can be found with *shape*, and its size with *size*

In [18]:
y.reshape(3,-1).shape

(3, 2)

In [22]:
y.dtype

dtype('int64')

In [11]:
y.size

6

In [13]:
x.shape

(1, 4)

In [14]:
x.size

4

In [15]:
x.mean()

2.5

In [16]:
x.std()

1.118033988749895

You can access the elements in the array by index. 
There are multiple ways to access the element in the array

In [35]:
x = np.array([[1,2,3]])
x[0][1]

2

In [27]:
y[0]

array([1, 2, 3])

In [36]:
y[0],y[0][0],y[0][1],y[0][2]

(array([1, 2, 3]), 1, 2, 3)

In [37]:
y[1],y[1][0],y[1][1],y[1][2]

(array([4, 5, 6]), 4, 5, 6)

In [38]:
y[0,0],y[0,1],y[0,2],y[1,0],y[1,1],y[1,2]

(1, 2, 3, 4, 5, 6)

In this form, the first index represents the row and the second index represents the column.

You can also use slices to obtain a section of the array:

In [39]:
# What result will you obtain after this operation? 
y[:,:2]

array([[1, 2],
       [4, 5]])

In [42]:
# What result will you obtain after this operation? 
y[:,-2:]

array([[2, 3],
       [5, 6]])

In [43]:
# you an also access mutiple rows or columns by index
y[:,[0,1]]

array([[1, 2],
       [4, 5]])

In [44]:
y[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [46]:
y[:,::2]

array([[1, 3],
       [4, 6]])

NumPy includes methods to generate arrays that have a structure. 

- *arange* -> generates arrays that are in order and evenly spaced,
- *linspace* -> generates an array of n equally spaced elements starting from a defined begining and end points

In [48]:
# np.arange requires three parameters: 
# The starting point, the end point, and the increment

# NOTE: the end point is not inclusive

np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [56]:
large_array = np.arange(0,2000,1)
large_array[:100]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [50]:
large_array[-100:]

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999])

In [51]:
large_array.size

2000

In [60]:
# np.linspace requires three parameters: 
# The starting point, the end point, and 
# the number of elements

# NOTE: the end point is inclusive

np.linspace(0.5, 3, 6)

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [63]:
np.linspace(0, 1999, 2000)

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 1.997e+03, 1.998e+03,
       1.999e+03])

NumPy includes some predefined arrays that can make your life easier

In [80]:
np.zeros((5,5)), np.ones((5,5)), np.eye(5)

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

In [81]:
np.zeros_like(y), np.ones_like(y)

(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]]))

In [89]:
a = np.zeros((1,3))
a[0]

array([0., 0., 0.])

In [ ]:
np.zeros_like(x)

In [ ]:
np.ones((5, 5))

In [91]:
np.empty((5, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [95]:
np.empty((1,5))

array([[1., 1., 1., 1., 1.]])

In [93]:
np.empty((5))

array([1., 1., 1., 1., 1.])

You can use the assigment operator to modify one or multiple elements in your array

In [96]:
# if you don't provide the increment, np.arange will
# use a default value of 1
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [97]:
#to change the element in the index position 4, we can do
a[4] = 10
a

array([ 1,  2,  3,  4, 10,  6])

In [98]:
# to change the elements from 4 to the end we can do
a[4:] = [45,32]
a

array([ 1,  2,  3,  4, 45, 32])

In [99]:
#python will let you know if you made a mistake
a[4:] = [43,32,55]

ValueError: cannot copy sequence with size 3 to array axis with dimension 2

In [102]:
# exercise
# to change the elements from index 2 to 5 (inclusive) to zero.
# we can do??
a[2:6] = np.zeros((1,4)) 
a

array([1, 2, 0, 0, 0, 0])

Exercise:

Create a zero array b with shape 2 by 2, and set 
$$
    𝑏=\begin{bmatrix}1&2 \\ 3& 4\end{bmatrix}
$$
using array indexing.

In [108]:
b = np.zeros((2,2))
#b[:,0] = np.array([[1,3]])
b[0,0] = 1
b

array([[1., 0.],
       [0., 0.]])

NumPy has powerful broadcasting abilities. You can do mathematical operation with arrays of different sizes and NumPy will take care of the operation if possible

## Operations with scalars 

In [109]:
b =  np.array([[0,1],[2,3]])
c = 2

In [110]:
b+c

array([[2, 3],
       [4, 5]])

In [111]:
b-c

array([[-2, -1],
       [ 0,  1]])

In [112]:
b*c

array([[0, 2],
       [4, 6]])

In [113]:
b/c

array([[0. , 0.5],
       [1. , 1.5]])

In [114]:
b**c

array([[0, 1],
       [4, 9]])

## Operations between arrays

In [ ]:
b =  np.array([[0,1],[2,3]])
d =  np.array([[4,5],[6,7]])

In [ ]:
b+d

In [ ]:
b-d

In [ ]:
b*d

In [ ]:
b/d

In [ ]:
b**d

The *, /, and ** operations are operating on an element by element basis. 

## Operations between arrays of different sizes

In [116]:
b =  np.array([[0,2],[3,4]])
d =  np.array([[4],[5]])

b, d

(array([[0, 2],
        [3, 4]]),
 array([[4],
        [5]]))

In [117]:
b+d

array([[4, 6],
       [8, 9]])

Can you explain what is going on? 

In [ ]:
b-d

In [118]:
b*d

array([[ 0,  8],
       [15, 20]])

In [119]:
b/d

array([[0. , 0.5],
       [0.6, 0.8]])

In [120]:
b**d

array([[   0,   16],
       [ 243, 1024]])

## Matrix Multiplication

In [122]:
b =  np.array([[0,1],[2,3]])
d =  np.array([[4,5],[6,7]])
e =  np.array([[4],[5]])
f =  np.array([[4,5]])

In [123]:
b@d, np.matmul(b,d)

(array([[ 6,  7],
        [26, 31]]),
 array([[ 6,  7],
        [26, 31]]))

In [124]:
b@e

array([[ 5],
       [23]])

In [125]:
# NumPy will tell you when you make a mistake
b@f

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [127]:
# the .T atributes computes the transpose of a matrix
# it has precedence over other operations
b@(f.T)

array([[ 5],
       [23]])

NumPy can also apply logical operations between arrays and scalars or between two arrays of the same size

In [13]:
import numpy as np
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [8]:
x>3

array([False, False,  True,  True,  True, False])

In [7]:
%%timeit
l = []
for number in x:
    l.append(number>3)
    
#print(l)

2.5 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Python can index elements of an array that satisfy a logical expression.

In [9]:
x[x>3]

array([4, 5, 9])

In [10]:
# you can also use multiple conditions 
x[np.logical_or(x<3,x>=5)]

array([1, 2, 5, 9])

In [11]:
x[np.logical_and(x<=9,x>=5)]

array([5, 9])

you can also use the assignment operator to modify an array based on conditions

In [14]:
y = x[x>3]
y

array([4, 5, 9])

In [15]:
y[y>=9] = 0
y

array([4, 5, 0])